services:
  postgres:
    image: postgres:16-alpine
    container_name: neo_postgres
    environment:
      POSTGRES_DB: neo_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-multiple-dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d neo_analytics"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  analytics-service:
    container_name: neo_analytics_service
    build:
      context: ./AnaliticsService
      dockerfile: Dockerfile
    env_file:
      - ./AnaliticsService/.env
    environment:
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
    volumes:
      - ./AnaliticsService/keys/public_key.pem:/app/keys/public_key.pem:ro
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  tasks-bank-service:
    container_name: neo_tasks_bank_service
    build:
      context: ./TasksBankService
      dockerfile: Dockerfile
    env_file:
      - ./TasksBankService/.env
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@postgres:5432/neo_tasks_bank
      JWT_PUBLIC_KEY_PATH: /app/keys/public_key.pem
    volumes:
      - ./AnaliticsService/keys/public_key.pem:/app/keys/public_key.pem:ro
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  ws-cursor-service:
    container_name: neo_ws_cursor_service
    build:
      context: ./WSCursorService
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    restart: unless-stopped
    
  app:
    build:
      context: ./core-service
      dockerfile: Dockerfile
    env_file:
      - ./core-service/.env
    container_name: java-business-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  ws-code-service:
    container_name: neo_ws_code_service
    build:
      context: ./WSCodeService
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    restart: unless-stopped

volumes:
  postgres_data:

