services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-business-app
    ports:
      - "8080:8080"
    env_file:
      - path: .env
        required: true
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:18-alpine
    container_name: coding_board_postgres
    restart: always
    env_file:
      - path: .env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
