services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-business-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:18-alpine
    container_name: coding_board_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB:-coding_board_db}
      POSTGRES_USER: ${POSTGRESQL_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD:-strong_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME:-postgres} -d ${POSTGRESQL_DB:-coding_board_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
