openapi: 3.0.4
info:
  title: NEO CODING BOARD API
  description: |-
    API для платформы лайв-кодинга. Позволяет создавать комнаты для интервью, 
    регистрировать кандидатов и управлять процессом собеседования.
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Rooms
    description: Управление комнатами и сессиями интервью
  - name: Code
    description: Работа с кодом кандидата и снимками (snapshots)
  - name: Notes
    description: Приватные заметки интервьюера
paths:
  /rooms:
    post:
      tags:
        - Rooms
      summary: Создание новой комнаты для интервью.
      operationId: createRoome
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                titleRoom:
                  type: string
                  example: "Title Room"
                nameVacancy:
                  type: string
                  example: "Java Developer"
      responses:
        "201":
          description: Комната успешно создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomCreateResponse"
    get:
      tags:
        - Rooms
      summary: Список комнат, проведенных текущим интервьюером, с пагинацией.
      operationId: getRoomsList
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Успешное получение списка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomListResponse"
  /rooms/all:
    get:
      tags:
        - Rooms
      summary: Получение всех уникальных комнат всех интервьюеров, с пагинацией.
      operationId: getAllRooms
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, FINISHED]
      responses:
        "200":
          description: Успешное получение списка всех комнат
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomListResponse"

  /rooms/{idRoom}:
    delete:
      tags:
        - Rooms
      summary: Удаление комнаты.
      operationId: deleteRoom
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Комната успешно удалена

  /rooms/join-info/{idRoom}:
    get:
      tags:
        - Rooms
      summary: Получение информации о комнате по ссылке.
      x-notes: еще подумать как реализовать вход по ссылке
      operationId: getJoinInfo
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Информация получена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JoinInfoResponse"

  /rooms/register/{idRoom}:
    post:
      tags:
        - Rooms
      summary: Регистрация кандидата в комнате.
      operationId: registerCandidate
      x-notes: продумать может быть и ввод почты.
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nameCandidate:
                  type: string
                  example: "Басманов Павел Николаевич"
      responses:
        "200":
          description: Регистрация успешна
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationResponse"

  /rooms/finish/{idRoom}:
    patch:
      tags:
        - Rooms
      summary: Завершение интервью.
      operationId: finishRoom
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                codeResolution:
                  type: string
                  enum: [PASSED, REJECTED]
      responses:
        "200":
          description: Интервью завершено
          content:
            application/json:
              schema:
                type: object
                properties:
                  idRoom:
                    type: string
                  timeEnd:
                    type: string
                    format: date-time

  /rooms/{idRoom}/code/latest:
    get:
      tags:
        - Code
      summary: Получение последнего среза кода.
      description: Возвращает актуальное состояние кода в комнате на текущий момент.
      operationId: getLatestCode
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Успешное получение кода
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CodeSnapshot"

  /rooms/{idRoom}/code/snapshots:
    get:
      tags:
        - Code
      summary: Получение всех снимков кода без пагинации.
      description: Возвращает полный список всех сохраненных состояний кода для данной комнаты.
      operationId: getAllCodeSnapshots
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Список всех снимков получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/CodeSnapshot"

  /rooms/{idRoom}/code/history:
    get:
      tags:
        - Code
      summary: История изменений кода с пагинацией.
      description: Позволяет просматривать этапы решения задачи постранично.
      operationId: getCodeHistory
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Страница истории получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/CodeSnapshot"
                  page:
                    $ref: "#/components/schemas/PageInfo"

  /rooms/{idRoom}/notes:
    post:
      tags:
        - Notes
      summary: Создание новой заметки.
      description: Добавляет заметку интервьюера. Сервер автоматически вычисляет `timeOffset` от старта сессии.
      operationId: createNote
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                textContent:
                  type: string
                  description: Содержание заметки
                  example: "Решил использовать метод двух указателей"
      responses:
        "201":
          description: Заметка успешно создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"

    get:
      tags:
        - Notes
      summary: Получение всех заметок комнаты.
      description: Возвращает список всех заметок для конкретного интервью (только для интервьюера/HR).
      operationId: getRoomNotes
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Список заметок получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  listNotes:
                    type: array
                    items:
                      $ref: "#/components/schemas/NoteResponse"

  /rooms/{idRoom}/notes/paged:
    get:
      tags:
        - Notes
      summary: Получение заметок комнаты с пагинацией.
      description: Возвращает постраничный список заметок для конкретного интервью.
      operationId: getRoomNotesPaged
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: Страница списка заметок получена
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: "#/components/schemas/NoteResponse"
                  page:
                    $ref: "#/components/schemas/PageInfo"

  /rooms/{idRoom}/notes/{idNote}:
    patch:
      tags:
        - Notes
      summary: Обновление содержимого заметки.
      description: Обновляет текст заметки. Время от начала интервью (timeOffset) не меняется, но выставляется поле timeUpdated.
      operationId: updateNote
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
        - name: idNote
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                textContent:
                  type: string
                  description: Новое содержание заметки
                  example: "Обновленный текст комментария"
      responses:
        "200":
          description: Заметка успешно обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NoteResponse"
    delete:
      tags:
        - Notes
      summary: Удаление заметки.
      operationId: deleteNote
      parameters:
        - name: idRoom
          in: path
          required: true
          schema:
            type: string
        - name: idNote
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Заметка удалена

components:
  schemas:
    RoomCreateResponse:
      type: object
      properties:
        idRoom:
          type: string
          example: "uuid-789"
        url:
          type: string
          example: "https://neo.hack/room/uuid-789/join"

    RoomListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/RoomSummary"
        page:
          $ref: "#/components/schemas/PageInfo"

    PageInfo:
      type: object
      properties:
        size:
          type: integer
          description: Размер страницы
          example: 10
        number:
          type: integer
          description: Номер страницы
          example: 0
        totalElements:
          type: integer
          description: Общее количество элементов
          example: 9
        totalPages:
          type: integer
          description: Общее количество страниц
          example: 1

    RoomSummary:
      type: object
      properties:
        idRoom:
          type: string
        nameCandidate:
          type: string
        status:
          type: string
        dateStart:
          type: string
          format: date-time
        dateEnd:
          type: string
          format: date-time
        timeOffset:
          type: string
          description: Время от начала интервью в формате mm:ss
          example: "10:30"

    JoinInfoResponse:
      type: object
      properties:
        idRoom:
          type: string
        nameVacancy:
          type: string
          example: "Kotlin Developer"

    RegistrationResponse:
      type: object
      properties:
        tokenAccess:
          type: string
        tokenRefresh:
          type: string

    CodeSnapshot:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор снимка
          example: "snap-123"
        textCode:
          type: string
          description: Полное содержимое редактора кода
          example: "fun main() {\n    println(\"Hello\")\n}"
        language:
          type: string
          description: Язык программирования, на котором пишет кандидат
          example: "kotlin"
        timeCreated:
          type: string
          format: date-time
          description: Метка времени создания снимка в БД

    WebSocketCodeUpdate:
      type: object
      description: Структура сообщения для обмена через WebSocket (/app/code/{idRoom}/update)
      x-notes: ws/app/code/{idRoom}/update
      x-notes1: подумать нужно ли хранить яп
      properties:
        textCode:
          type: string
          description: Текущий текст в редакторе
        language:
          type: string
          description: Язык программирования, на котором пишет кандидат
          example: "kotlin"

    NoteResponse:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор заметки
          example: "note-555"
        textContent:
          type: string
          description: Текст комментария интервьюера
          example: "Нашел проблему с двумя указателями"
        timeOffset:
          type: string
          description: Время от начала интервью в формате mm:ss
          example: "10:30"
        timeCreated:
          type: string
          format: date-time
          description: Абсолютное время создания записи в БД
        timeUpdated:
          type: string
          format: date-time
          description: Время последнего обновления заметки в БД
